# config/app_config.yaml
app:
  name: "IDPS + Ticket System"
  version: "2.0.0"
  debug: false

ticket_app:
  window_title: "Система обработки заявок на билеты v2.0"
  window_size: "1800x1000"
  db_storage_file: "employees_database.json"

ocr:
  scale_factor: 3
  tesseract_config: "--psm 6 --oem 3"
  tesseract_lang: "rus+eng"
  min_text_length: 30

routes:
  - "Абакан - Алматы"
  - "Абакан - Астана"
  - "Абакан - Ашхабад"
  - "Абакан - Белград"
  - "Абакан - Бишкек"
  - "Абакан - Дамаск"
  - "Абакан - Дели"
  - "Абакан - Душанбе"
  - "Абакан - Ереван"
  - "Абакан - Загреб"
  - "Абакан - Минск"
  - "Алеппо - Абакан"
  - "Алеппо - Москва"
  - "Алеппо - Санкт-Петербург"
  - "Санкт-Петербург - Фергана"
  - "Санкт-Петербург - Ташкент"
  - "Санкт-Петербург - Бишкек"
  - "Санкт-Петербург - Алматы"
  - "Санкт-Петербург - Астана"
  - "Санкт-Петербург - Душанбе"
  - "Санкт-Петербург - Ереван"
  - "Санкт-Петербург - Минск"
  - "Москва - Фергана"
  - "Москва - Ташкент"
  - "Москва - Бишкек"
  - "Москва - Алматы"
  - "Москва - Астана"
  - "Фергана - Санкт-Петербург"
  - "Ташкент - Санкт-Петербург"
  - "Бишкек - Санкт-Петербург"
  - "Алматы - Санкт-Петербург"
  - "Астана - Санкт-Петербург"
  - "Душанбе - Санкт-Петербург"
  - "Ереван - Санкт-Петербург"
  - "Минск - Санкт-Петербург"

reasons:
  - "Увольнение"
  - "Межвахтовый отдых"
  - "Возвращение из отпуска"
  - "Устройство на работу"
  - "Перевод в др. ОП"
  - "Командировка"
  - "Разъездной характер работы"
  - "Ежегодный отпуск"
  - "Больничный"
  - "Межвахта"
